import { Router } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth';
import { validateBody } from '../middleware/validate';
import { asyncHandler } from '../middleware/asyncHandler';
import { organizationService } from '../../modules/organizations/organizationService';
import { repositoryService } from '../../modules/repositories/repositoryService';
import { pullRequestService } from '../../modules/reviews/pullRequestService';
import { prDetailService } from '../../modules/reviews/prDetailService';
import { startReview } from '../../modules/reviews/reviewEnqueueService';
import { logger } from '../../utils/logger';
import { AppError } from '../../errors/AppError';

const router: Router = Router();

router.use(requireAuth);

/**
 * "Simulate PR" — dev-friendly webhook injector.
 *
 * Real webhooks rely on a git provider firing a request at the API. For demo
 * environments (and for local development) we let an authenticated user fake
 * that event: pick an organization + repo, optionally provide a PR URL, and
 * the API enqueues a review exactly the way a real webhook would.
 *
 * Unlike the /webhooks/* endpoints, this skips signature verification — the
 * request is already authenticated via JWT.
 */

const simulateSchema = z.object({
  organizationId: z.string().uuid(),
  repositoryId: z.string().uuid().optional(),
  pullRequestUrl: z.string().url().optional(),
});

router.post(
  '/',
  validateBody(simulateSchema),
  asyncHandler(async (req, res) => {
    const body = req.body as z.infer<typeof simulateSchema>;
    const userId = req.user!.id;
    const actor = req.user!.name || req.user!.email;

    const org = await organizationService.assertOwned(body.organizationId, userId);

    // Resolve target repo: either the explicit repositoryId or the first
    // repo for the org if a URL is provided.
    let repository = body.repositoryId
      ? await repositoryService.assertOwned(body.repositoryId, userId)
      : null;
    if (!repository) {
      const repos = await repositoryService.listForOrganization(userId, org.id);
      repository = repos[0] ?? null;
    }
    if (!repository) {
      throw AppError.badRequest(
        'No repository to simulate against. Add a repo to this organization first.',
      );
    }

    // If no PR URL was supplied, fabricate one using a synthetic numeric id.
    // This lets the demo work end-to-end without a real upstream PR — the
    // review pipeline will hit the provider with the fake URL and gracefully
    // fail at the fetch step, marking the review as 'failed' with a clear
    // error. The PR + timeline rows are persisted regardless.
    const fakeId = String(Math.floor(Math.random() * 9000) + 1000);
    const prUrl =
      body.pullRequestUrl ?? synthesizePrUrl(repository.repoUrl, repository.provider, fakeId);
    const externalId = extractExternalId(prUrl, repository.provider) ?? fakeId;

    // Materialise / refresh PR row.
    const pr = await pullRequestService.createPlaceholder({
      repositoryId: repository.id,
      prUrl,
      externalId,
    });

    // For synthetic PRs, pre-fill title/author so the row doesn't show up as
    // "(pending)" — the pipeline can't fetch real metadata from a fake URL.
    // Real PR URLs skip this: their metadata is fetched from the provider
    // during the review pipeline and would just be overwritten here.
    if (!body.pullRequestUrl) {
      await pullRequestService.upsert({
        repositoryId: repository.id,
        prUrl,
        metadata: {
          externalId,
          title: `Simulated PR #${externalId}`,
          description: 'Generated by Simulate PR.',
          author: actor,
          sourceBranch: 'simulate/' + externalId,
          targetBranch: repository.defaultBranch ?? 'main',
          filesChanged: 0,
          additions: 0,
          deletions: 0,
        },
      });
    }

    // Always record an "opened" timeline event so the activity feed reflects
    // the simulation.
    await prDetailService.appendEvent({
      pullRequestId: pr.id,
      eventType: 'opened',
      actor,
      payload: { simulated: true },
    });

    const { reviewId } = await startReview({
      userId,
      pullRequestUrl: prUrl,
      organizationId: org.id,
      logContext: '[simulate]',
    });

    logger.info('[simulate] queued review', {
      orgId: org.id,
      repoId: repository.id,
      prId: pr.id,
      reviewId,
    });

    res.status(202).json({
      reviewId,
      pullRequest: pr,
      simulated: !body.pullRequestUrl,
    });
  }),
);

function synthesizePrUrl(repoUrl: string, provider: string, prId: string): string {
  const trimmed = repoUrl.replace(/\/+$/, '');
  if (provider === 'github') return `${trimmed}/pull/${prId}`;
  if (provider === 'gitlab') return `${trimmed}/-/merge_requests/${prId}`;
  return `${trimmed}/pull-requests/${prId}`;
}

function extractExternalId(prUrl: string, provider: string): string | null {
  const match =
    provider === 'gitlab'
      ? /\/merge_requests\/(\d+)/.exec(prUrl)
      : /(?:pull|pull-requests)\/(\d+)/.exec(prUrl);
  return match?.[1] ?? null;
}

export default router;
